service: serverlessapi

# AWS base details
provider:
  name: aws
  runtime: nodejs24.x
  region: eu-west-2

# Lambda functions that authorize data access using JWT access token
functions:
  
  getUserInfo:
    handler: dist/getUserInfo.handler
    package:
      include:
        - dist/getUserInfo.js
        - api.config.json
        - package.json
    events:
      - http: 
          path: /userinfo
          method: get

  getCompanyList:
    handler: dist/getCompanyList.handler
    package:
      include:
        - dist/getCompanyList.js
        - data/companyList.json
        - api.config.json
        - package.json
    events:
      - http: 
          path: /companies
          method: get

  getCompanyTransactions:
    handler: dist/getCompanyTransactions.handler
    package:
      include:
        - dist/getCompanyTransactions.js
        - data/companyList.json
        - data/companyTransactions.json
        - api.config.json
        - package.json
    events:
      - http: 
          path: /companies/{id}/transactions
          method: get
          request: 
            parameters: 
              paths: 
                id: true

# Disable the default build which we are overriding with a bundler
build:
  esbuild: false

# Exclude all files by default and choose files in the function packaging above
package:
  individually: true
  patterns:
  - '!/**'
  
# Support running locally
plugins:
  - serverless-offline

resources:
  Resources:
  
    # Take ownership of the API domain
    ApiDomain:
      Type: AWS::ApiGateway::DomainName
      Properties:
        DomainName: api.authsamples.com
        EndpointConfiguration:
          Types:
            - REGIONAL
        RegionalCertificateArn: 'arn:aws:acm:eu-west-2:090109105180:certificate/953873fe-43f7-4e6f-90fe-3227ce194d6e'
        SecurityPolicy: SecurityPolicy_TLS13_1_3_2025_09
        EndpointAccessMode: STRICT

    # Configure the main API route that requires JWT access tokens
    ApiDomainMapping:
      Type: AWS::ApiGateway::BasePathMapping
      Properties:
        DomainName: !Ref ApiDomain
        BasePath: investments
        RestApiId:
          Ref: ApiGatewayRestApi
        Stage: deployed

    # Configure a web route to APIs that requires SameSite cookies, for requests from the SPA running in Cloudfront
    BffDomainMapping:
      Type: AWS::ApiGateway::BasePathMapping
      Properties:
        DomainName:
          Fn::ImportValue: BffDomainName
        BasePath: investments
        RestApiId:
          Ref: ApiGatewayRestApi
        Stage: deployed

    # Configure a web route to APIs that requires SameSite cookies, for requests from the SPA running on a development computer
    BffDomainDevMapping:
      Type: AWS::ApiGateway::BasePathMapping
      Properties:
        DomainName:
          Fn::ImportValue: BffDomainDevName
        BasePath: investments
        RestApiId:
          Ref: ApiGatewayRestApi
        Stage: deployed

    # Limit Cloudwatch log retention 
    GetUserInfoLogGroup:
      Type: 'AWS::Logs::LogGroup'
      Properties:
        RetentionInDays: '5'
    GetCompanyListLogGroup:
      Type: 'AWS::Logs::LogGroup'
      Properties:
        RetentionInDays: '5'
    GetCompanyTransactionsLogGroup:
      Type: 'AWS::Logs::LogGroup'
      Properties:
        RetentionInDays: '5'
